api = "0.7"

[buildpack]
  description = "A buildpack for starting a unicorn server for a Ruby app"
  homepage = "https://github.com/paketo-buildpacks/unicorn"
  id = "paketo-buildpacks/unicorn"
  keywords = ["ruby", "unicorn"]
  name = "Paketo Buildpack for Unicorn"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/unicorn/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"

[[targets.distros]]
name = "ubuntu"
version = "18.04"

[[targets.distros]]
name = "ubuntu"
version = "22.04"
